/**
 * Application-wide constants
 */

export type CategoryItem = {
  value: string;
  count: number;
};

/**
 * List of available product categories
 * These categories are used for filtering products in the browse experience
 */
export const CATEGORIES: CategoryItem[] = [
  { value: "Appliances", count: 0 },
  { value: "Computers & Tablets", count: 0 },
  { value: "Cell Phones", count: 0 },
  { value: "Cell Phone Accessories", count: 0 },
  { value: "Audio", count: 0 },
  { value: "Small Kitchen Appliances", count: 0 },
  { value: "Cameras & Camcorders", count: 0 },
  { value: "Car Electronics & GPS", count: 0 },
  { value: "TV & Home Theater", count: 0 },
  { value: "Cell Phone Cases & Clips", count: 0 },
  { value: "Health, Fitness & Beauty", count: 0 },
  { value: "Digital Camera Accessories", count: 0 },
  { value: "Ranges, Cooktops & Ovens", count: 0 },
  { value: "Home Audio", count: 0 },
  { value: "Office & School Supplies", count: 0 },
  { value: "Printer Ink & Toner", count: 0 },
  { value: "iPhone Accessories", count: 0 },
  { value: "iPad & Tablet Accessories", count: 0 },
  { value: "Deck Installation Parts", count: 0 },
  { value: "iPhone Cases & Clips", count: 0 },
  { value: "Video Games", count: 0 },
  { value: "Headphones", count: 0 },
  { value: "Personal Care & Beauty", count: 0 },
  { value: "Refrigerators", count: 0 },
  { value: "Laptop Accessories", count: 0 },
  { value: "Printer Ink", count: 0 },
  { value: "Smart Home", count: 0 },
  { value: "Coffee, Tea & Espresso", count: 0 },
  { value: "Dash Installation Kits", count: 0 },
  { value: "Laptops", count: 0 },
  { value: "All Refrigerators", count: 0 },
  { value: "Office Electronics", count: 0 },
  { value: "Speakers", count: 0 },
  { value: "Musical Instruments", count: 0 },
  { value: "Laptop Bags & Cases", count: 0 },
  { value: "Toys, Games & Drones", count: 0 },
  { value: "Washers & Dryers", count: 0 },
  { value: "Wearable Technology", count: 0 },
  { value: "All Desktops", count: 0 },
  { value: "Hard Drives & Storage", count: 0 },
  { value: "Ranges", count: 0 },
  { value: "Car Audio", count: 0 },
  { value: "Housewares", count: 0 },
  { value: "Mice & Keyboards", count: 0 },
  { value: "Monitors", count: 0 },
  { value: "A/V Cables & Connectors", count: 0 },
  { value: "Microwaves", count: 0 },
  { value: "Printers, Ink & Toner", count: 0 },
  { value: "All Unlocked Cell Phones", count: 0 },
  { value: "Unlocked Cell Phones", count: 0 },
  { value: "Telephones & Communication", count: 0 },
  { value: "Tablets", count: 0 },
  { value: "Apple Watch", count: 0 },
  { value: "Dishwashers", count: 0 },
  { value: "TVs", count: 0 },
  { value: "All Microwaves", count: 0 },
  { value: "All Printers", count: 0 },
  { value: "Camcorder Accessories", count: 0 },
  { value: "Household Batteries", count: 0 },
  { value: "Digital Cameras", count: 0 },
  { value: "Built-In Dishwashers", count: 0 },
  { value: "Dryers", count: 0 },
  { value: "Cables & Connectors", count: 0 },
  { value: "TV Stands", count: 0 },
  { value: "Apple Watch Accessories", count: 0 },
  { value: "Office Furniture & Storage", count: 0 },
  { value: "Camera Lenses", count: 0 },
  { value: "LED Monitors", count: 0 },
  { value: "Household Essentials", count: 0 },
  { value: "Screen Protectors", count: 0 },
  { value: "USB Flash Drives", count: 0 },
  { value: "Kitchen Gadgets", count: 0 },
  { value: "Blenders & Juicers", count: 0 },
  { value: "Cooktops", count: 0 },
  { value: "Toner", count: 0 },
  { value: "Networking & Wireless", count: 0 },
  { value: "Wall Ovens", count: 0 },
  { value: "Coffee Makers", count: 0 },
  { value: "Towers Only", count: 0 },
  { value: "Earbud & In-Ear Headphones", count: 0 },
  { value: "Hair Care", count: 0 },
  { value: "Range Hoods", count: 0 },
  { value: "Electric Ranges", count: 0 },
  { value: "All TV Stands", count: 0 },
  { value: "All Cell Phones with Plans", count: 0 },
  { value: "Mice", count: 0 },
  { value: "Specialty Appliances", count: 0 },
  { value: "Camera Batteries & Power", count: 0 },
  { value: "Gas Ranges", count: 0 },
  { value: "Deck Harnesses", count: 0 },
  { value: "Mixers & Mixer Accessories", count: 0 },
  { value: "Smartwatch Accessories", count: 0 },
  { value: "Smartwatches & Accessories", count: 0 },
  { value: "Blenders", count: 0 },
  { value: "Memory Cards", count: 0 },
  { value: "Wall Mount Range Hoods", count: 0 },
  { value: "All Laptops", count: 0 },
  { value: "Cases", count: 0 },
  { value: "Name Brands", count: 0 },
  { value: "TV Mounts", count: 0 },
];

/**
 * Algolia search configuration
 */
export const SEARCH_CONFIG = {
  indexName: 'instant_search',
  hitsPerPage: 20,
} as const;
